### ISSUE TITLE
Issue with pod file after upgrading to 3.0.0

### ISSUE THREAD

**Issue by premtemp1** [roughike/flutter_facebook_login#189]
Hello,
  I having some pod file issue after upgrading to 3.0.0.  

I change the pod file but I still get the error.. I get no errors with (2.0.0).. 

Please help

-- podfile --
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
pod 'FBSDKCoreKit', '4.39.1'
pod 'FBSDKLoginKit', '4.39.1'

-----error ----

Running pod install...                                              0.8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - FBSDKCoreKit
      - FBSDKLoginKit
      - Flutter
      - file_picker
      - firebase_analytics
      - firebase_auth
      - firebase_core
      - firebase_crashlytics
      - firebase_dynamic_links
      - firebase_messaging
      - firebase_remote_config
      - flutter_facebook_login
      - flutter_statusbarcolor
      - google_sign_in
      - keyboard_visibility
      - location
      - package_info
      - path_provider
      - share
      - shared_preferences
      - url_launcher

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `file_picker` from `.symlinks/plugins/file_picker/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
    -> Fetching podspec for `firebase_dynamic_links` from `.symlinks/plugins/firebase_dynamic_links/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `firebase_remote_config` from `.symlinks/plugins/firebase_remote_config/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `flutter_statusbarcolor` from `.symlinks/plugins/flutter_statusbarcolor/ios`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `keyboard_visibility` from `.symlinks/plugins/keyboard_visibility/ios`
    -> Fetching podspec for `location` from `.symlinks/plugins/location/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
      In snapshot (Podfile.lock):
        FBSDKLoginKit (= 4.39.1)

      In Podfile:
        FBSDKLoginKit (= 4.39.1)

        flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
          FBSDKLoginKit (~> 5.5)

    Specs satisfying the `FBSDKLoginKit (= 4.39.1), FBSDKLoginKit (= 4.39.1), FBSDKLoginKit (~> 5.5)` dependency were found, but
    they required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in
    unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb:91:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:909:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in
    `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error running pod install

**Comment by Armanoide** [comment]
Make sure you have `platform :ios, '10.0'` in the Podfile
and run `pod update FBSDKCoreKit` and `pod update FBSDKLoginKit` then `pod install`
it should work now.

**Comment by raphFlash** [comment]
I tried that but i still have that error

Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKAppEventsState.m:181:29: error: no known class method for selector 'JSONStringForObject:error:invalidObjectHandler:'
      return [FBSDKBasicUtility JSONStringForObject:events error:NULL invalidObjectHandler:NULL];

**Comment by raphFlash** [comment]
I managed to compile thanks to 
https://github.com/roughike/flutter_facebook_login/issues/185#issuecomment-536812802

**Comment by premtemp1** [comment]
@raphFlash ..

I tried  but I am still getting errors..

Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
Fetching podspec for `file_picker` from `.symlinks/plugins/file_picker/ios`
Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
Fetching podspec for `firebase_dynamic_links` from `.symlinks/plugins/firebase_dynamic_links/ios`
Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
Fetching podspec for `firebase_remote_config` from `.symlinks/plugins/firebase_remote_config/ios`
Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
Fetching podspec for `flutter_statusbarcolor` from `.symlinks/plugins/flutter_statusbarcolor/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Fetching podspec for `keyboard_visibility` from `.symlinks/plugins/keyboard_visibility/ios`
Fetching podspec for `location` from `.symlinks/plugins/location/ios`
Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `share` from `.symlinks/plugins/share/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
[!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
  In Podfile:
    FBSDKLoginKit (= 4.39.1)

    flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
      FBSDKLoginKit (~> 5.5)

Specs satisfying the `FBSDKLoginKit (= 4.39.1), FBSDKLoginKit (~> 5.5)` dependency were found, but they required a higher minimum deployment target.

**Comment by raphFlash** [comment]
Did you delete these files and folders "Podfile.lock, .symlinks, Pods" ?

**Comment by edwardmelody** [comment]
@premtemp1 

Remove 

```
pod 'FBSDKCoreKit', '4.39.1'
pod 'FBSDKLoginKit', '4.39.1'
```

from your Podfile

do not insert "pod ..." that following by Facebook Docs or Firebase or others. This plugin or other plugin will inject the code by themselves when flutter building. Stay your Podfile to original. Just edit iOS platform to 9.0.

Then follow the step from the issue #185

**Comment by premtemp1** [comment]
@edwardmelody 
Thanks..
